import {readFile,writeFile,mkdir,cp} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {makeIcon} from './icons.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),dest=path.join(root,'www');
await mkdir(dest,{recursive:true});
let html=await readFile(path.join(root,'../public/index.html'),'utf8');
const api=process.env.FENGJI_API_URL||'https://weather-rtygbwwwerr.netlify.app/api';
if(new URL(api).protocol!=='https:')throw Error('数据服务必须使用 HTTPS');
html=html.replace("location.protocol==='file:'?'http://127.0.0.1:8877/api':'/api'",JSON.stringify(api));
html=html.replace('content="width=device-width,initial-scale=1"','content="width=device-width,initial-scale=1,viewport-fit=cover"');
html=html.replace('https://unpkg.com/leaflet@1.9.4/dist/leaflet.css','./vendor/leaflet.css').replace('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js','./vendor/leaflet.js');
html=html.replace('</head>','<meta name="theme-color" content="#061018"><link rel="stylesheet" href="./mobile.css"></head>').replace('</body>','<script src="./mobile.js"></script></body>').replaceAll('本机数据桥','风迹数据服务');
await writeFile(path.join(dest,'index.html'),html);
html=html.replace('</head>','<link rel="manifest" href="./manifest.webmanifest"><link rel="apple-touch-icon" href="./icon-180.png"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="风迹"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"></head>');
html=html.replace('</body>','<script>if("serviceWorker" in navigator && !window.Capacitor?.isNativePlatform())navigator.serviceWorker.register("./sw.js").catch(console.warn);</script></body>');
await writeFile(path.join(dest,'index.html'),html);
for(const size of [180,192,512])await writeFile(path.join(dest,`icon-${size}.png`),makeIcon(size));
for(const file of ['manifest.webmanifest','sw.js'])await cp(path.join(root,'src',file),path.join(dest,file));
await cp(path.join(root,'node_modules/leaflet/dist'),path.join(dest,'vendor'),{recursive:true});
for(const file of ['mobile.css','mobile.js'])await cp(path.join(root,'src',file),path.join(dest,file));
console.log('已构建风迹手机版，API: '+api);
